# Generated by Django 2.2 on 2019-04-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='counter',
            field=models.IntegerField(default=5, verbose_name=5),
            preserve_default=False,
        ),
    ]
